import "./style.css";
const I={
hero:"https://images.pexels.com/photos/30683099/pexels-photo-30683099.jpeg?auto=compress&cs=tinysrgb&w=1600",
girl:"https://images.pexels.com/photos/31703299/pexels-photo-31703299.jpeg?auto=compress&cs=tinysrgb&w=1000",
girl2:"https://images.pexels.com/photos/28121572/pexels-photo-28121572.jpeg?auto=compress&cs=tinysrgb&w=1000",
boy:"https://images.pexels.com/photos/31977204/pexels-photo-31977204.jpeg?auto=compress&cs=tinysrgb&w=1000",
boy2:"https://images.pexels.com/photos/5325899/pexels-photo-5325899.jpeg?auto=compress&cs=tinysrgb&w=1000",
festive:"https://images.pexels.com/photos/17408546/pexels-photo-17408546.jpeg?auto=compress&cs=tinysrgb&w=1200"
};
const items=[
["Wide-Leg Denim","Girls • Denim","₹1,499","Trending",I.girl,"Relaxed denim for an everyday fashion look."],
["Oversized Tee","Teen • Casual","₹699","New",I.boy2,"An easy oversized silhouette for current street style."],
["Utility Cargo","Girls • Bottoms","₹1,299","Trending",I.girl2,"A practical cargo look with a modern fit."],
["Denim Shirt Look","Boys • Casual","₹899","New",I.boy,"A smart casual option for weekends and outings."],
["Everyday Denim","Girls • Casual","₹999","Edit",I.girl2,"Easy denim and tee styling for everyday wear."],
["Classic Tee + Denim","Boys • Everyday","₹999","Bestseller",I.boy2,"Simple, comfortable and easy to style."],
["Festive Kurta","Traditional • Boys","₹1,499","Festive",I.festive,"A traditional direction for festivals and family functions."],
["Celebration Look","Traditional • Girls","₹1,899","Festive",I.festive,"An occasion-ready look for celebrations."]
];
const card=(x,i)=>`<article class="product"><button class="photo" data-i="${i}"><img src="${x[4]}" alt="${x[0]}" loading="lazy"><span>${x[3]}</span><b>View look ↗</b></button><div class="meta"><div><small>${x[1]}</small><h3>${x[0]}</h3></div><strong>${x[2]}</strong></div><button class="ask text-link" data-i="${i}">Ask about this style ↗</button></article>`;
document.querySelector("#root").innerHTML=`
<header><a class="brand" href="#home"><i>F</i><span><b>FASHIONHUB</b><small>LOCAL STYLE • NEW DROPS</small></span></a><button class="menu">☰</button><nav><a href="#girls">Girls</a><a href="#boys">Boys</a><a href="#teen">Teen Edit</a><a href="#traditional">Traditional</a><a href="#new">New In</a><a href="#visit">Store</a></nav><a class="cta" href="#visit">Visit store ↗</a></header>
<main>
<section class="hero" id="home"><div class="hero-copy"><small class="eyebrow">FASHIONHUB / NEW SEASON</small><h1>Style they’ll<br><em>want to wear.</em></h1><p>A modern local clothing store for kids, tweens and teens — from jeans and tees to festive looks.</p><div><a class="btn" href="#new">Explore styles ↗</a><a class="plain" href="#visit">Visit the store</a></div><aside>✓ New styles regularly &nbsp; ✓ Ask us to source a style &nbsp; ✓ Try before you buy</aside></div><div class="hero-img"><img src="${I.girl}" alt="Young girl wearing modern casual fashion"><label>NEW<br><b>DROP</b><br>2026</label></div></section>
<div class="age"><b>SHOP BY AGE</b><a href="#girls">Kids</a><a href="#teen">Tweens</a><a href="#teen">Teens</a><a href="#traditional">Festive</a><span>Don't see it? <strong>Tell us what you want.</strong></span></div>
<section class="intro"><div><small class="eyebrow">01 / THE STORE ONLINE</small><h2>Not just clothes.<br><em>A whole look.</em></h2></div><p>Think of this as the shop's digital catalogue. Customers can see the kind of styles you carry, decide what they like, then message or visit the store to check sizes, colours and actual stock.</p></section>
<section class="collections" id="girls"><div class="head"><div><small class="eyebrow">SHOP BY COLLECTION</small><h2>Find their <em>style.</em></h2></div><p>Everyday fashion, teen trends and occasion wear — organised so parents and kids can find something quickly.</p></div><div class="collections-grid"><a href="#new"><img src="${I.girl}" alt="Girls fashion"><div><small>01</small><h3>Girls</h3><p>Denim • Tops • Co-ords</p></div></a><a href="#new"><img src="${I.boy}" alt="Boys fashion"><div><small>02</small><h3>Boys</h3><p>Tees • Shirts • Denim</p></div></a><a href="#teen"><img src="${I.boy2}" alt="Teen fashion"><div><small>03</small><h3>Teen Edit</h3><p>Oversized • Street • Trending</p></div></a><a href="#traditional"><img src="${I.festive}" alt="Traditional children's fashion"><div><small>04</small><h3>Traditional</h3><p>Festive • Functions • Family</p></div></a></div></section>
<section class="catalog" id="boys"><div class="head" id="new"><div><small class="eyebrow">02 / NEW IN</small><h2>What’s <em>trending.</em></h2></div><p>Show customers the current direction of the store without turning a local shop into a complicated ecommerce site.</p></div><div class="filters"><button class="active" data-filter="all">All</button><button data-filter="girls">Girls</button><button data-filter="boys">Boys</button><button data-filter="teen">Teen</button><button data-filter="traditional">Traditional</button></div><div class="products" id="products"></div></section>
<section class="request" id="teen"><div><small class="eyebrow">YOUR STYLE / YOUR REQUEST</small><h2>Seen a look you<br><em>want us to find?</em></h2></div><div><p>Send a photo, screenshot or simply say “blue wide-leg jeans for a 14-year-old”. The store can check current stock or help bring a similar style.</p><a class="light-btn" href="#visit">Request a style ↗</a></div></section>
<section class="story" id="traditional"><img src="${I.festive}" alt="Children in traditional clothing"><div><small class="eyebrow">03 / OCCASIONS</small><h2>From everyday<br>to <em>festive.</em></h2><p>Birthdays, festivals, family functions or a last-minute outfit — keep one local store in mind for the next look.</p><ul><li>01 &nbsp; Everyday</li><li>02 &nbsp; Birthday & Party</li><li>03 &nbsp; Festivals</li><li>04 &nbsp; Family Functions</li></ul><a class="btn" href="#new">See the edit ↗</a></div></section>
<section class="visit" id="visit"><div><small class="eyebrow">04 / VISIT FASHIONHUB</small><h2>Come in.<br><em>Let’s find the fit.</em></h2><p>Online browsing is only the beginning. Visit the store to check fabric, fit, colours and available sizes.</p><div class="facts"><span><b>STORE</b><br>Your shop address</span><span><b>HOURS</b><br>Add timings</span><span><b>WHATSAPP</b><br>Add store number</span></div></div><form id="form"><small class="eyebrow">QUICK ENQUIRY</small><h3>Tell us what you're looking for.</h3><label>Name<input required placeholder="Your name"></label><label>Looking for<select><option>Girls clothing</option><option>Boys clothing</option><option>Teen / trending style</option><option>Traditional / festive</option><option>Specific style / screenshot</option></select></label><label>Message<textarea placeholder="Age, size, colour, occasion..."></textarea></label><button class="btn">Send enquiry ↗</button><small id="success"></small></form></section>
</main><footer><div class="brand"><i>F</i><span><b>FASHIONHUB</b><small>LOCAL STYLE • NEW DROPS</small></span></div><p>Come for the clothes.<br><em>Stay for the style.</em></p><div class="footer-links"><a href="#girls">Girls</a><a href="#boys">Boys</a><a href="#teen">Teen</a><a href="#traditional">Festive</a><a href="#visit">Visit</a></div><small class="note">Demo concept — replace store details before client delivery.</small></footer>
<div class="modal" id="modal"><div class="shade"></div><div class="modal-box"><button class="close">×</button><img id="mimg"><div><small class="eyebrow" id="mtype"></small><h2 id="mname"></h2><strong id="mprice"></strong><p id="mdesc"></p><a class="btn" href="#visit" id="mclose">Ask about this style ↗</a></div></div></div>`;
const grid=document.querySelector("#products");function render(f="all"){grid.innerHTML=items.filter(x=>f==="all"||x[1].toLowerCase().includes(f)).map(card).join("")}render();
document.addEventListener("click",e=>{if(e.target.closest(".menu"))document.querySelector("nav").classList.toggle("open");if(e.target.closest("nav a"))document.querySelector("nav").classList.remove("open");const f=e.target.closest("[data-filter]");if(f){document.querySelectorAll("[data-filter]").forEach(x=>x.classList.remove("active"));f.classList.add("active");render(f.dataset.filter)}const t=e.target.closest("[data-i]");if(t){const x=items[+t.dataset.i];document.querySelector("#mimg").src=x[4];document.querySelector("#mtype").textContent=x[1];document.querySelector("#mname").textContent=x[0];document.querySelector("#mprice").textContent=x[2];document.querySelector("#mdesc").textContent=x[5];document.querySelector("#modal").classList.add("show")}if(e.target.closest(".close,.shade,#mclose"))document.querySelector("#modal").classList.remove("show");if(e.target.closest(".ask")){const x=items[+e.target.closest(".ask").dataset.i];document.querySelector("textarea").value=`Hi, I'm interested in "${x[0]}". Please let me know available sizes/colours.`;document.querySelector("#visit").scrollIntoView({behavior:"smooth"})}});
document.querySelector("#form").addEventListener("submit",e=>{e.preventDefault();document.querySelector("#success").textContent="Demo enquiry submitted — connect this to WhatsApp for the real store."});
